In [1]:
import numpy as np 
import pandas as pd 


df = pd.read_csv('/kaggle/input/shoes-logistic-regression/shoe - shoe.csv')

df.head(5)

   size(cm) class(y)
0     9.500   Female
1    10.125     Male
2    10.410     Male
3     9.810   Female
4    11.050     Male

In [2]:
df['class(y)'] = df['class(y)'].map({'Female': 1, 'Male': 0})

df.head(5)

   size(cm)  class(y)
0     9.500         1
1    10.125         0
2    10.410         0
3     9.810         1
4    11.050         0

In [3]:
y=df.drop(['size(cm)'], axis=1)

x=df.drop(['class(y)'], axis=1)

x.head(5)

   size(cm)
0     9.500
1    10.125
2    10.410
3     9.810
4    11.050

In [4]:
y.head(5)

   class(y)
0         1
1         0
2         0
3         1
4         0

In [5]:
from sklearn.linear_model import LogisticRegression

clf= LogisticRegression()

clf.fit(x, y)

clf.predict(x)

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1])

In [6]:
Y_predict = clf.predict_proba(x)

Y_predict

array([[0.22697155, 0.77302845],
       [0.60261758, 0.39738242],
       [0.7622543 , 0.2377457 ],
       [0.3986433 , 0.6013567 ],
       [0.94513014, 0.05486986],
       [0.1048049 , 0.8951951 ],
       [0.20475417, 0.79524583],
       [0.82996773, 0.17003227],
       [0.33764173, 0.66235827],
       [0.30334042, 0.69665958],
       [0.40495737, 0.59504263],
       [0.76698218, 0.23301782],
       [0.64270836, 0.35729164],
       [0.92262639, 0.07737361],
       [0.82242418, 0.17757582],
       [0.88139619, 0.11860381],
       [0.53507945, 0.46492055],
       [0.47604803, 0.52395197],
       [0.70601519, 0.29398481],
       [0.83725425, 0.16274575],
       [0.61823389, 0.38176611],
       [0.16526816, 0.83473184],
       [0.11778331, 0.88221669],
       [0.8607854 , 0.1392146 ],
       [0.28694843, 0.71305157],
       [0.78523331, 0.21476669],
       [0.7005333 , 0.2994667 ],
       [0.90166638, 0.09833362],
       [0.7807699 , 0.2192301 ],
       [0.88139619, 0.11860381],
       [0.54812276, 0.45187724],
       [0.46296265, 0.53703735],
       [0.75746084, 0.24253916],
       [0.27109755, 0.72890245],
       [0.6244146 , 0.3755854 ],
       [0.14793483, 0.85206517],
       [0.12054056, 0.87945944],
       [0.82622828, 0.17377172],
       [0.2763197 , 0.7236803 ],
       [0.15468074, 0.84531926]])

In [10]:
x

    size(cm)
0      9.500
1     10.125
2     10.410
3      9.810
4     11.050
5      9.150
6      9.450
7     10.570
8      9.710
9      9.650
10     9.820
11    10.420
12    10.190
13    10.910
14    10.550
15    10.730
16    10.020
17     9.930
18    10.300
19    10.590
20    10.150
21     9.350
22     9.200
23    10.660
24     9.620
25    10.460
26    10.290
27    10.810
28    10.450
29    10.730
30    10.040
31     9.910
32    10.400
33     9.590
34    10.160
35     9.300
36     9.210
37    10.560
38     9.600
39     9.320

In [8]:
clf.coef_

array([[-2.62699981]])

In [9]:
 clf.intercept_

array([26.18198935])